# Site settings
title: Solace Samples
baseurl: "" 
repository: https://github.com/SolaceSamples



#----------------------------------------------------
# Generally don't modify items below this point

url: "solacesamples.github.io" # the base hostname & protocol for your site

# Google services
google_analytics: UA-3921398-7

# Build settings
markdown: kramdown